### ISSUE TITLE
Update README to build/run the project

### ISSUE THREAD

**Issue by marquesarthur** [FrameNetBrasil/fnbr#1]
Hi,

As steps toward contributing to the project, I would like to get directions on how to build/run the system. 

For that, it would presumably be necessary to create a local MySQL database and run the web app.

I've checked the `./docs/database/scripts` and some of them modify tables that I could not find the create tabla scripts, e.g. in migrations-3.3.sql you have

```
ALTER TABLE `mfn_db`.`Lemma` 
ADD COLUMN `idUDPOS` INT(11) UNSIGNED NULL DEFAULT NULL AFTER `idEntity`,
```

However, I could not find a create table Lemma script.
That being said, I've skimmed through the `Lemma.php` and `LemmaMap.php` files and the latter has some database logic (it can be just ORM mapping, or perhaps it is bootstrapping the DB instantiation)

If I can discuss with the contributors and set up a local environment, I would be happy to update the README file such that others can set a local copy of the environment up and running.

**Comment by elymatos** [comment]
Hi @marquesarthur 
Thank you very much for your interest on FrameNet Brasil Webtool.
Actually, to make the sharing and collaboration easier, we have created a new repository at https://github.com/FrameNetBrasil/webtool 
Please, access the new repository and try to install, following the instructions. Let me know if it is necessary complement something in this instructions.
Thanks

**Comment by marquesarthur** [comment]
Closing the issue. New discussion under: https://github.com/FrameNetBrasil/webtool/issues/1
